#! /usr/bin/perl

use strict;
use warnings;
use JSON;

my $SINGLE_MYSQL_DATADIR='/data/mysql/';
my $MULTI_MYSQL_DATADIR_PREFIX='/data/';
my $json_obj = JSON->new;
my @data_array=();
my $json_ref;
$json_ref->{data}=\@data_array;




if( -d $SINGLE_MYSQL_DATADIR ){
    my %mysql_info;
    $mysql_info{'{#MYSQLPORT}'}=3306;
    $mysql_info{'{#SOCKET}'}='/data/mysql/mysql.sock';
    push( @{$json_ref->{data}}, \%mysql_info );
}else{
    for( my $port=3306; $port<3320; $port++ ){
        my $dir_name = $MULTI_MYSQL_DATADIR_PREFIX."/data${port}/mysql";
        if( -d $dir_name ){
            my %mysql_info;
            $mysql_info{'{#MYSQLPORT}'}=$port;
            $mysql_info{'{#SOCKET}'}   =$dir_name."/mysql.sock";
    push( @{$json_ref->{data}}, \%mysql_info );
        }
    }
}

my $json_str = $json_obj->pretty->encode($json_ref);
print $json_str;
